### ISSUE TITLE
Styled JSX error

### ISSUE THREAD

**Issue by armandabric** [RyanClementsHax/storybook-addon-next#4]
**Describe the bug**

When a mount a `<style jsx global>` element I got an error:

```
ReferenceError: _JSXStyle is not defined
    at GlobalStyles (http://localhost:3000/main.iframe.bundle.js:68147:34)
    at renderWithHooks (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:141207:18)
    at mountIndeterminateComponent (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:144033:13)
    at beginWork (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:145271:16)
    at HTMLUnknownElement.callCallback (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:130167:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:130216:16)
    at invokeGuardedCallback (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:130278:31)
    at beginWork$1 (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:150181:7)
    at performUnitOfWork (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:148993:12)
    at workLoopSync (http://localhost:3000/vendors-node_modules_ebay_nice-modal-react_lib_esm_index_js-node_modules_gogaille_sanity-imag-919ca0.iframe.bundle.js:148924:5)
```
And my `GlobalStyles` component:

```jsx
import theme from "guidelines/Theme/theme";

const GlobalStyles = () => (
  <style global jsx>{`
    html {
      min-height: 100vh;
    }

    body,
    #__next {
      /**
       * Mobile viewport bug fix
       * @see https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/
       */
      min-height: 100vh;
      min-height: fill-available;

      background-color: ${theme.color.background.cream};
    }

    html,
    body {
      margin: 0;
      padding: 0;
    }

    * {
      box-sizing: border-box;
    }
  `}</style>
);
```

**Additional context**
Next.js v12.0.7

**Comment by RyanClementsHax** [comment]
Thanks for opening the issue!

I used this code in the nextv12 example and wasn't able to reproduce an error. Could you provide a minimal reproduction case?

**Comment by shouze** [comment]
@RyanClementsHax do you think it could be fixed by https://github.com/RyanClementsHax/storybook-addon-next/pull/25?

**Comment by RyanClementsHax** [comment]
@shouze Unlikely. I've encountered this error when I was originally creating the support for styled jsx. I fixed it before publishing 1.0.

The problem I'm having here is that I need a reproduction case as I'm unable to reproduce it myself. Once I have that, I can dive deeper into the problem.

Are you experiencing this issue?
