### ISSUE TITLE
Next 12.1.5 error: Failed to parse src "static/media/public/nyan-cat.png"

### ISSUE THREAD

**Issue by rsanchez** [RyanClementsHax/storybook-addon-next#72]
### Describe the bug

As of Next 12.1.5, this addon no longer seems to work with Next Image.

Full error message:

```
Error: Failed to parse src "static/media/public/nyan-cat.png" on `next/image`, if using relative image it must start with a leading slash "/" or be an absolute URL (http:// or https://)
    at defaultLoader (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:55971:23)
    at defaultImageLoader (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:55790:16)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:55755:39
    at Array.map (<anonymous>)
    at generateImgAttrs (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:55755:24)
    at ImageElement (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:55896:183)
    at renderWithHooks (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:79513:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:82339:13)
    at beginWork (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:83577:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-config-entr-68d96e.iframe.bundle.js:68473:14)
```

### Your minimal, reproducible example

https://github.com/rsanchez-forks/storybook-addon-next/tree/next-12.1.5-issue/examples/nextv12

### Steps to reproduce

1. In `examples/nextv12`, run `yarn add next@12.1.5`
2. Run `yarn storybook`
3. Go to Nextjs Images Page in storybook
4. Observer error in storybook

### Expected behavior

As a user, expect next-image to work within Storybook.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1555" alt="Screen Shot 2022-04-16 at 10 35 42 PM" src="https://user-images.githubusercontent.com/227340/163698062-4232f2e2-2b29-497c-ace9-85eaa8d6de6c.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 100.0.4896.75

### storybook-addon-next version

Main branch, Commit hash a7efc092c5db5b6e96c9dfeb478bca01567fe1c6

### Additional context

Next 12.1.4 does not have the same issue.

**Comment by RyanClementsHax** [comment]
Thanks for opening the issue! Do you currently have a workaround?

**Comment by rsanchez** [comment]
No workaround currently, other than just using Next 12.1.4. Seems like maybe a lot of changes under the hood to next/image in 12.1.5.

**Comment by LZL0** [comment]
I am experiencing the same issue. I was wondering why, but @rsanchez is probably correct.

**Comment by jeroenroumen-acc** [comment]
Experiencing the same issue. Reverting to `12.1.4` for now seems to solve it.

**Comment by RyanClementsHax** [comment]
So it seems that the following code no longer works
```js
// .storybook/preview.js
import * as NextImage from "next/image";

const OriginalNextImage = NextImage.default;

Object.defineProperty(NextImage, "default", {
  configurable: true,
  value: (props) => <OriginalNextImage {...props} unoptimized />,
});
```
This has been the convention to getting `next/image` working in storybook for a long time. I'm not sure why it is broken now. [This is a compare between next 12.1.4 and 12.1.5](https://github.com/vercel/next.js/compare/v12.1.4...v12.1.5) and nothing stands out to me as a major change.

I will continue to look into this, but if anyone has any insight, feel free to chip in.

**Comment by LoicMahieu** [comment]
Like @jeroenroumen-acc  , rollback to `12.1.4` fix the issue...

**Comment by RyanClementsHax** [comment]
Thank you all for your patience! I'm working with Next.js to figure out what the issue exactly is and how to remediate it

**Comment by rsanchez** [comment]
@RyanClementsHax Thanks for tracking this down. Is that fix something you plan to incorporate into this plugin? Or are you suggesting we use that fix in our own code?

**Comment by RyanClementsHax** [comment]
I might put it in the repo but I was hoping to have clarification from the nextjs team if this is a bug on their end first.

I'm kinda torn on what to do. Put a workaround in this repo and risk breaking changes for y'all if nextjs decides to fix this problem, or wait until a decision is reached so we can implement a proper fix if needed.

**Comment by RyanClementsHax** [comment]
Thanks all for your patience. I know this was frustrating.
