### ISSUE TITLE
Error when starting, when using Typescript

### ISSUE THREAD

**Issue by tremby** [RyanClementsHax/storybook-addon-next#80]
### Describe the bug

From a fresh Next installation with Typescript, and a fresh Storybook installation with Webpack 5, I am getting a `Error: Cannot find module 'webpack/lib/util/makeSerializable.js'` error when I try to start Storybook.

### Your minimal, reproducible example

See commands below

### Steps to reproduce

1. `npx create-next-app@latest bug --typescript`
2. `cd bug`
3. `npx sb init --builder webpack5` -- in my test I said yes to the linter question
4. `npm i -D --force storybook-addon-next`
5. Edit .storybook/main.js, add `storybook-addon-next` to the end of the `addons` array
6. `npm run storybook`
7. See error:

```
Error: Cannot find module 'webpack/lib/util/makeSerializable.js'
Require stack:
- /tmp/bug/node_modules/@storybook/react-docgen-typescript-plugin/dist/dependency.js
- /tmp/bug/node_modules/@storybook/react-docgen-typescript-plugin/dist/plugin.js
- /tmp/bug/node_modules/@storybook/react-docgen-typescript-plugin/dist/index.js
- /tmp/bug/node_modules/@storybook/react/dist/cjs/server/framework-preset-react-docgen.js
- /tmp/bug/node_modules/@storybook/core-common/dist/cjs/presets.js
- /tmp/bug/node_modules/@storybook/core-common/dist/cjs/index.js
- /tmp/bug/node_modules/@storybook/core-server/dist/cjs/index.js
- /tmp/bug/node_modules/@storybook/core/dist/cjs/server.js
- /tmp/bug/node_modules/@storybook/core/server.js
- /tmp/bug/node_modules/@storybook/react/dist/cjs/server/index.js
- /tmp/bug/node_modules/@storybook/react/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/bug/node_modules/@storybook/react-docgen-typescript-plugin/dist/dependency.js:6:55)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /tmp/bug/node_modules/@storybook/react-docgen-typescript-plugin/dist/plugin.js:108:42
    at Hook.eval [as call] (eval at create (/tmp/bug/node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:374:1)
    at Hook.CALL_DELEGATE [as _call] (/tmp/bug/node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/tmp/bug/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compiler.js:1122:26)
    at /tmp/bug/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compiler.js:1166:29 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/bug/node_modules/@storybook/react-docgen-typescript-plugin/dist/dependency.js',
    '/tmp/bug/node_modules/@storybook/react-docgen-typescript-plugin/dist/plugin.js',
    '/tmp/bug/node_modules/@storybook/react-docgen-typescript-plugin/dist/index.js',
    '/tmp/bug/node_modules/@storybook/react/dist/cjs/server/framework-preset-react-docgen.js',
    '/tmp/bug/node_modules/@storybook/core-common/dist/cjs/presets.js',
    '/tmp/bug/node_modules/@storybook/core-common/dist/cjs/index.js',
    '/tmp/bug/node_modules/@storybook/core-server/dist/cjs/index.js',
    '/tmp/bug/node_modules/@storybook/core/dist/cjs/server.js',
    '/tmp/bug/node_modules/@storybook/core/server.js',
    '/tmp/bug/node_modules/@storybook/react/dist/cjs/server/index.js',
    '/tmp/bug/node_modules/@storybook/react/bin/index.js'
  ]
}
```

### Expected behavior

Storybook starts

### How often does this bug happen?

Every time

### Platform

- OS: Linux
- Browser: n/a

### storybook-addon-next version

1.6.2

**Comment by tremby** [comment]
Looks like this is a Storybook issue; see https://github.com/storybookjs/storybook/issues/18197
